/* Generated by batch-launcher plugin. */
class Main {

    def initService
    def sshd
    def grailsApplication


    def init = {
        ->
        println "main.init ${Thread.currentThread()}"

        initService.init()
        sshd.start()
    }

    def run = {/* Map */ context ->
        synchronized(sshd) {
            sshd.wait()
        }
    }

    def destroy = {
        ->
        println "main.destroy ${Thread.currentThread()}"
        sshd.stop()
        synchronized(sshd) {
            sshd.notifyAll()
        }
    }
}
